language: node_js
node_js:
- 'stable'
before_install:
- openssl aes-256-cbc -K $encrypted_4e543ecb61f7_key -iv $encrypted_4e543ecb61f7_iv -in key.json.enc -out key.json -d
before_script:
- gulp lint
env:
- DATASET_ID=gcloud-todos
